---
clone:
  depth: 1
kind: pipeline
name: STRIX kernel
steps:
  - name: compile
    image: panchajanya1999/archlinux:latest
    commands:
      - bash build.sh
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
